name: dotnet package
on: 
  push:
    branches:
      - 'main'
      - '_init'

env:
  buildConfig: Release
  srcProjects: ./src/**/*.csproj
  testProjects: ./tests/**/*.csproj
  currentVersion: 0.1.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{matrix.dotnet-version}}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{matrix.dotnet-version}}
      - name: create build version
        run: echo "BUILD_VERSION=${{ env.currentVersion }}-alpha.${{ github.run_id }}" >> $GITHUB_ENV

      - name: confirm build version
        run: echo $BUILD_VERSION

      - name: dotnet restore
        run: |
          find . -type f -name *.csproj \
            -exec dotnet restore {} \;

      - name: dotnet build
        run: |
          find . -type f -name *.csproj \
            -exec dotnet build {} \
            --no-restore \
            --configuration ${{ env.buildConfig }} \
            /p:Version=$BUILD_VERSION \;

      - name: dotnet test
        run: | 
          find ${{ env.testProjects }} -type f \
            -exec dotnet test {} \
            --no-build \
            --configuration ${{ env.buildConfig }} \;

      - name: dotnet pack
        run: |
          find ${{ env.srcProjects }} -type f \
            -exec dotnet pack \
            --no-build \
            --configuration ${{ env.buildConfig }} \
            --output staging/packages \
            /p:Version=$BUILD_VERSION \;

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Nomads
          path: staging/**/*.nupkg

